//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt_kirill
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Служба доставки.
    /// </summary>
    // *** Start programmer edit section *** (СлужбаДоставки CustomAttributes)

    // *** End programmer edit section *** (СлужбаДоставки CustomAttributes)
    [AutoAltered()]
    [Caption("Служба доставки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СлужбаДоставкиE", new string[] {
            "Номер as \'Номер\'",
            "Наименвоание as \'Наименвоание\'",
            "Адрес as \'Адрес\'",
            "НомерТелефона as \'Номер телефона\'"})]
    [View("СлужбаДоставкиL", new string[] {
            "Номер as \'Номер\'",
            "Наименвоание as \'Наименвоание\'",
            "Адрес as \'Адрес\'",
            "НомерТелефона as \'Номер телефона\'"})]
    public class СлужбаДоставки : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fНаименвоание;
        
        private string fАдрес;
        
        private int fНомерТелефона;
        
        // *** Start programmer edit section *** (СлужбаДоставки CustomMembers)

        // *** End programmer edit section *** (СлужбаДоставки CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (СлужбаДоставки.Адрес CustomAttributes)

        // *** End programmer edit section *** (СлужбаДоставки.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Адрес Get start)

                // *** End programmer edit section *** (СлужбаДоставки.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (СлужбаДоставки.Адрес Get end)

                // *** End programmer edit section *** (СлужбаДоставки.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Адрес Set start)

                // *** End programmer edit section *** (СлужбаДоставки.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (СлужбаДоставки.Адрес Set end)

                // *** End programmer edit section *** (СлужбаДоставки.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Наименвоание.
        /// </summary>
        // *** Start programmer edit section *** (СлужбаДоставки.Наименвоание CustomAttributes)

        // *** End programmer edit section *** (СлужбаДоставки.Наименвоание CustomAttributes)
        [StrLen(255)]
        public virtual string Наименвоание
        {
            get
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Наименвоание Get start)

                // *** End programmer edit section *** (СлужбаДоставки.Наименвоание Get start)
                string result = this.fНаименвоание;
                // *** Start programmer edit section *** (СлужбаДоставки.Наименвоание Get end)

                // *** End programmer edit section *** (СлужбаДоставки.Наименвоание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Наименвоание Set start)

                // *** End programmer edit section *** (СлужбаДоставки.Наименвоание Set start)
                this.fНаименвоание = value;
                // *** Start programmer edit section *** (СлужбаДоставки.Наименвоание Set end)

                // *** End programmer edit section *** (СлужбаДоставки.Наименвоание Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (СлужбаДоставки.Номер CustomAttributes)

        // *** End programmer edit section *** (СлужбаДоставки.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Номер Get start)

                // *** End programmer edit section *** (СлужбаДоставки.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (СлужбаДоставки.Номер Get end)

                // *** End programmer edit section *** (СлужбаДоставки.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Номер Set start)

                // *** End programmer edit section *** (СлужбаДоставки.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (СлужбаДоставки.Номер Set end)

                // *** End programmer edit section *** (СлужбаДоставки.Номер Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (СлужбаДоставки.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (СлужбаДоставки.НомерТелефона CustomAttributes)
        public virtual int НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (СлужбаДоставки.НомерТелефона Get start)

                // *** End programmer edit section *** (СлужбаДоставки.НомерТелефона Get start)
                int result = this.fНомерТелефона;
                // *** Start programmer edit section *** (СлужбаДоставки.НомерТелефона Get end)

                // *** End programmer edit section *** (СлужбаДоставки.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СлужбаДоставки.НомерТелефона Set start)

                // *** End programmer edit section *** (СлужбаДоставки.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (СлужбаДоставки.НомерТелефона Set end)

                // *** End programmer edit section *** (СлужбаДоставки.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СлужбаДоставкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СлужбаДоставкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СлужбаДоставкиE", typeof(IIS.Proekt_kirill.СлужбаДоставки));
                }
            }
            
            /// <summary>
            /// "СлужбаДоставкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СлужбаДоставкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СлужбаДоставкиL", typeof(IIS.Proekt_kirill.СлужбаДоставки));
                }
            }
        }
    }
}
