//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt_kirill
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Хранение.
    /// </summary>
    // *** Start programmer edit section *** (Хранение CustomAttributes)

    // *** End programmer edit section *** (Хранение CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ХранениеE", new string[] {
            "Номер as \'Номер\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаЗавершения as \'Дата завершения\'",
            "Продления as \'Продления\'"})]
    [AssociatedDetailViewAttribute("ХранениеE", "Посылка", "ПосылкаE", true, "", "Посылка", true, new string[] {
            ""})]
    [View("ХранениеL", new string[] {
            "Номер as \'Номер\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаЗавершения as \'Дата завершения\'",
            "Продления as \'Продления\'"})]
    public class Хранение : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private System.DateTime fДатаНачала;
        
        private System.DateTime fДатаЗавершения;
        
        private string fПродления;
        
        private IIS.Proekt_kirill.DetailArrayOfПосылка fПосылка;
        
        // *** Start programmer edit section *** (Хранение CustomMembers)

        // *** End programmer edit section *** (Хранение CustomMembers)

        
        /// <summary>
        /// ДатаЗавершения.
        /// </summary>
        // *** Start programmer edit section *** (Хранение.ДатаЗавершения CustomAttributes)

        // *** End programmer edit section *** (Хранение.ДатаЗавершения CustomAttributes)
        public virtual System.DateTime ДатаЗавершения
        {
            get
            {
                // *** Start programmer edit section *** (Хранение.ДатаЗавершения Get start)

                // *** End programmer edit section *** (Хранение.ДатаЗавершения Get start)
                System.DateTime result = this.fДатаЗавершения;
                // *** Start programmer edit section *** (Хранение.ДатаЗавершения Get end)

                // *** End programmer edit section *** (Хранение.ДатаЗавершения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Хранение.ДатаЗавершения Set start)

                // *** End programmer edit section *** (Хранение.ДатаЗавершения Set start)
                this.fДатаЗавершения = value;
                // *** Start programmer edit section *** (Хранение.ДатаЗавершения Set end)

                // *** End programmer edit section *** (Хранение.ДатаЗавершения Set end)
            }
        }
        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (Хранение.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (Хранение.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (Хранение.ДатаНачала Get start)

                // *** End programmer edit section *** (Хранение.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (Хранение.ДатаНачала Get end)

                // *** End programmer edit section *** (Хранение.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Хранение.ДатаНачала Set start)

                // *** End programmer edit section *** (Хранение.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (Хранение.ДатаНачала Set end)

                // *** End programmer edit section *** (Хранение.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Хранение.Номер CustomAttributes)

        // *** End programmer edit section *** (Хранение.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Хранение.Номер Get start)

                // *** End programmer edit section *** (Хранение.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Хранение.Номер Get end)

                // *** End programmer edit section *** (Хранение.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Хранение.Номер Set start)

                // *** End programmer edit section *** (Хранение.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Хранение.Номер Set end)

                // *** End programmer edit section *** (Хранение.Номер Set end)
            }
        }
        
        /// <summary>
        /// Продления.
        /// </summary>
        // *** Start programmer edit section *** (Хранение.Продления CustomAttributes)

        // *** End programmer edit section *** (Хранение.Продления CustomAttributes)
        [StrLen(255)]
        public virtual string Продления
        {
            get
            {
                // *** Start programmer edit section *** (Хранение.Продления Get start)

                // *** End programmer edit section *** (Хранение.Продления Get start)
                string result = this.fПродления;
                // *** Start programmer edit section *** (Хранение.Продления Get end)

                // *** End programmer edit section *** (Хранение.Продления Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Хранение.Продления Set start)

                // *** End programmer edit section *** (Хранение.Продления Set start)
                this.fПродления = value;
                // *** Start programmer edit section *** (Хранение.Продления Set end)

                // *** End programmer edit section *** (Хранение.Продления Set end)
            }
        }
        
        /// <summary>
        /// Хранение.
        /// </summary>
        // *** Start programmer edit section *** (Хранение.Посылка CustomAttributes)

        // *** End programmer edit section *** (Хранение.Посылка CustomAttributes)
        public virtual IIS.Proekt_kirill.DetailArrayOfПосылка Посылка
        {
            get
            {
                // *** Start programmer edit section *** (Хранение.Посылка Get start)

                // *** End programmer edit section *** (Хранение.Посылка Get start)
                if ((this.fПосылка == null))
                {
                    this.fПосылка = new IIS.Proekt_kirill.DetailArrayOfПосылка(this);
                }
                IIS.Proekt_kirill.DetailArrayOfПосылка result = this.fПосылка;
                // *** Start programmer edit section *** (Хранение.Посылка Get end)

                // *** End programmer edit section *** (Хранение.Посылка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Хранение.Посылка Set start)

                // *** End programmer edit section *** (Хранение.Посылка Set start)
                this.fПосылка = value;
                // *** Start programmer edit section *** (Хранение.Посылка Set end)

                // *** End programmer edit section *** (Хранение.Посылка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ХранениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ХранениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ХранениеE", typeof(IIS.Proekt_kirill.Хранение));
                }
            }
            
            /// <summary>
            /// "ХранениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ХранениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ХранениеL", typeof(IIS.Proekt_kirill.Хранение));
                }
            }
        }
    }
}
